#!/usr/bin/env sh
. "$(dirname "$0")/h"

echo "Running lint + format + docs generation before commit..."

npm run lint-staged || {
  printf "\n\nERROR: Lint issues were found in the committed files. Please address them before proceeding.\n\n\n\n"
  exit 1
}

npm run docs || {
  printf "\n\nERROR: Doc issues were found in the committed files. Please address them before proceeding.\n\n\n\n"
  exit 1
}

npm run format:fix || {
  printf "\n\nERROR: Format:fix issues were found in the committed files. Please address them before proceeding.\n\n\n\n"
  exit 1
}

echo "Post-commit checks complete."