#!/usr/bin/env sh
. "$(dirname "$0")/h"

echo "Running library coverage before push..."

npm run test:coverage:clean

npm run test:coverage || {
  printf "\n\nERROR: Test Coverage issues were found in the committed files. Please address them before proceeding.\n\n\n\n"
  exit 1
}

echo "Library coverage checks passed."